# Generated by Django 6.0.5 on 2026-06-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
