# Generated by Django 6.0.5 on 2026-07-03 13:54
# Modified: Now a no-op because customer fields were removed from 0001_initial.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = []
