# Generated by Django 6.0.5 on 2026-06-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockinitem_item_alter_stockopnameitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='Stok saat ini (dikelola langsung)'),
        ),
    ]
